language: python
dist: bionic

python:
 - 3.6
 - 3.7
 - 3.8

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=bandit

before_install:
 - sudo apt-get install -y p7zip-full
install:
 - pip install tox-travis codecov
script:
 - tox
after_success:
 - codecov
